### ISSUE TITLE
Batch Job Scheduling

### ISSUE THREAD

**Issue by rahnemon2011** [KnowledgeAssets/myskills-server#2]
The MySkills Server should provide the possibility to save the reports periodically. Because creating reports may take a while, It's better to create a Batch Job for it. For example, It can read and create reports for a group of records(e.g. 200 records) each time. It is possible to create a schedule to run the Batch Job, for example, each week.

**Comment by rahnemon2011** [comment]
The MySkills Server should provide the possibility to save the reports periodically. Because creating reports may take a while, It's better to create a Batch Job for it. For example, It can read and create reports for a group of records(e.g. 200 records) each time. It is possible to create a schedule to run the Batch Job, for example, each week.

**Comment by georgwittberger** [comment]
We should pospone this feature for the sake of better clarification about how to implement a scheduled creation of reports. It is also debatable how Spring Batch could be used here because taking a snapshot of a particular user skill priority report effectively must be an atomic operation which cannot be split into chunks, in my point of view.

**Comment by georgwittberger** [comment]
This topic is closed due to inactivity. We can open a new discussion as soon as we have a real use case for batch processing.
